name: Deploy Weather App to GitHub Pages

on:
    push:
        branches: ["main"]
        paths:
            - "week13/JsAssignment5-weatherApp/**" # Only run when weather app changes

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create config.js with API key
              run: |
                  cd week13/JsAssignment5-weatherApp
                  echo "export const API_KEY = '${{ secrets.WEATHER_API_KEY }}';" > config.js
                  echo "✅ config.js created successfully"

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GH_PAT }}
                  publish_dir: ./week13/JsAssignment5-weatherApp
                  destination_dir: week13/JsAssignment5-weatherApp
                  keep_files: false
